### ISSUE TITLE
Kirby 3?

### ISSUE THREAD

**Issue by louiswalch** [medienbaecker/kirby-fieldtoggle#12]
Any plan to port this to Kirby3?

**Comment by medienbaecker** [comment]
It's sadly not possible to port this plugin right now. See this for more information: https://github.com/getkirby/plugins/issues/34

**Comment by Amerlander** [comment]
I dont get what informations about why its not posivle to port this plugin to kirby v3 are behind your link. Has something changed since January?

**Comment by medienbaecker** [comment]
@Amerlander Unfortunately the repository changed. You're in luck however, as [Conditional Fields](https://getkirby.com/docs/guide/blueprints/fields#conditional-fields) are now part of the Kirby core.
