### ISSUE TITLE
Issues with Kirby 2.4?

### ISSUE THREAD

**Issue by Foddy** [medienbaecker/kirby-fieldtoggle#4]
Hi,

I tried to use this plugin with the newest Kirby v2.4 – but I am getting this error when I try to edit a page on the panel?

![fieldtoggle error](https://cloud.githubusercontent.com/assets/5302050/20461870/1e60fb5a-af0c-11e6-8149-195d03055215.png)

Thank you in advance!

**Comment by medienbaecker** [comment]
Hi Foddy,

I use this plugin on 2.4.0 too. The error message says there's no code Radio Field. That's really weird. I just used it on another freshly set up 2.4.0 and I can't reproduce this. Can you upload the `panel` and `kirby` folders again? Maybe there went something wrong uploading the files.

**Comment by stffndtz** [comment]
@Foddy 

Did you install it in the fields folder?

Just ran into the same issue because we did not RTFM.

**Comment by medienbaecker** [comment]
Oh, I didn't even think of that. Thanks @stffndtz! The error message says `site/plugins/fieldtoggle`, so that' probably the problem.
