### ISSUE TITLE
Missing CLI Support

### ISSUE THREAD

**Issue by maxxst** [medienbaecker/kirby-fieldtoggle#5]
Kirby CLI support would be awesome. I guess you would have to divide the plugin and the docs in two branches probably master and [gh-pages](https://pages.github.com)

**Comment by krisak** [comment]
Came here to say the same thing. The field installs but with wrong folder structure

![screen shot 2017-02-13 at 10 27 21](https://cloud.githubusercontent.com/assets/4954323/22877754/26ea59fc-f1d7-11e6-9804-253c666be7d2.png)

Seems like it could be possible to fix?

**Comment by medienbaecker** [comment]
@maxxst @krisak I just changed the folder structure and put the preview GIFs in a `preview` folder, that way it should work.

I wish there were an option for the `package.json` to use a subfolder as the root...

**Comment by krisak** [comment]
It is very basic yes and somewhat sucks, but kirby devs like to keep it simple.

Your edit though wont work. It is dumb it replicates the repo name so i guess you either have to change the repo name (not option) or the filenames.

![screen shot 2017-02-13 at 12 24 20](https://cloud.githubusercontent.com/assets/4954323/22881550/61d731d8-f1e7-11e6-834b-4f15963e447f.png)

I am looking at this https://github.com/getkirby-plugins/modules-plugin and it works with cli and it has differend names (modules-plugin modules.php). Cli either removes the -plugins or it takes the name from package.json and renames the folder. It is  "name": "modules" while yours is "name": "kirby-fieldtoggle",

**Comment by medienbaecker** [comment]
@krisak I have changed the name to just `fieldtoggle`, does it work for you now? Sorry for the wrong "fix". I have yet to try out the Kirby CLI for myself. It does have some advantages, but I'm not really a "command line" guy.

I do like the file builder though, so I made an Alfred workflow some time ago. Maybe I can emulate the plugin/field installer too some time.
![alfred](https://cloud.githubusercontent.com/assets/7975568/22882210/4f59b4c4-f1ea-11e6-8648-99aee604e080.gif)

**Comment by krisak** [comment]
Awesome it works now.
Well the CLI is not that critical it realy just installs to folders. 
You might aswell use
```
git clone https://github.com/medienbaecker/kirby-fieldtoggle.git fieldtoggle
```
but there is important distinction you have to already be in plugins folder. With kirby cli you are in root and just do
```
kirby plugin:install medienbaecker/kirby-fieldtoggle
```
and it will put it to right folder. Its a small difference but if you want to up your adoption you might ask kirby devs to add you to their plugins repo and then its just 

```
kirby plugin:install kirby-fieldtoggle
```
I install and update lot of plugins this way but mostly use it for
```
kirby update
```
Btw i use alfred too but if you use iterm and put it to show on hotkey its almost the same as alfred realy.

![itermhotkey](https://cloud.githubusercontent.com/assets/4954323/22884460/4804edb4-f1f5-11e6-9f56-61e19156b92b.gif)
