### ISSUE TITLE
Upper- and Lowercase differentiation

### ISSUE THREAD

**Issue by dkerzig** [medienbaecker/kirby-fieldtoggle#7]
Hi,
in the readme:

> As of version 2.3, Kirby converts every field name to lowercase in the panel. There's no differentiation between fieldName and fieldname. Thanks to LCD344 for testing that.

But the `fieldtoggle` only works for me if I explicitly use the lowercase version (e.g. `previewimage` for `previewImage`). Because I use camelCase ids in my blueprints it's always a hassle to rename only for the `fieldtoggle`-definitions (and I often accidentally forget it so it just doesn't work).

It would be great if you could ignore the case in the show/hide definitions :)

Dennis

**Comment by medienbaecker** [comment]
Hi Dennis,

I just pushed a commit that should allow you to use your camelCase field names in the blueprint.

Cheers,
Thomas
