### ISSUE TITLE
Independent width for answers

### ISSUE THREAD

**Issue by daybugging** [medienbaecker/kirby-fieldtoggle#9]
Let's say the panel field has `width: 1/4`, I think it would be useful to stack the radio buttons, you know? Otherwise even short text cannot be seen. Also, without the `width` attribute, they take up very much space, so it would be useful to separately define the width of each answer.

**Comment by medienbaecker** [comment]
That's already possible as it is a core feature of the radio field. You can use `columns: ` to define the number of columns for the options. For example:

```
label: Your field
type: fieldtoggle
columns: 1

```
That way there will be one option per row.
